### PR TITLE
BUG: fix default for post_tfm_kwargs, fixes Inconsistent syllable error

### PR DESCRIPTION
**Pull request by zhileiz1992**
BUG: fix default for post_tfm_kwargs, fixes Inconsistent syllable error

### CODE REVIEW

**Comment by NickleDave** [comment]
Thank you @zhileiz1992, I really appreciate this!

I'm dealing with a deadline + something I owe @yardencsGitHub but I will test this early this week so we can get it merged in and release a new version for you

**Review by NickleDave — CHANGES_REQUESTED** [review]
This looks like just what we need, thank you @zhileiz1992!

Very minor change:
can you please modify the commit message so that it references the number of the issue you opened?

Like this:
`BUG: Fix default for post_tfm_kwargs, fixes #697`

That way GitHub will close the issue automatically when we merge this one, and also we'll be able to trace back to the original issue if we need to for some reason.

One way you can do this is in the terminal is like so:
`git commit --amend`

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

Just let me know if I'm not explaining that clearly. Appreciate it!

**Comment by zhileiz1992** [comment]
I did the 'git commit --amend' thing, do I still need to git push? 
Thanks!

**Comment by NickleDave** [comment]
Looks like that fixed it, thanks! Testing now

**Comment by NickleDave** [comment]
Tests passed, thank you @zhileiz1992! Much appreciated. I merged in and will release a new bugfix version, then get it on PyPI and conda-forge for you ASAP.

**Comment by NickleDave** [comment]
@all-contributors please add @zhileiz1992 for code

**Pull request merged**
